# Generated by Django 3.0.8 on 2020-12-29 21:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_discussion_forum_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_MCAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=300)),
                ('correct', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_type', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.AddField(
            model_name='discussion',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz_mcanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.Quiz_Questions'),
        ),
    ]
