# Generated by Django 3.0.8 on 2020-12-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_discussion_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
    ]
