# Generated by Django 3.0.8 on 2020-12-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0005_learningmaterial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningmaterial',
            old_name='title',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='quiz_questions',
            name='solution',
            field=models.CharField(default='a', max_length=10),
            preserve_default=False,
        ),
    ]
